"""
digest.py  —  the DAILY OPS BRIEF. A product doesn't hand you a one-off report;
it pushes fresh, decision-ready intelligence every morning. This generates a
dated digest a control-room desk can read in 60 seconds (and a hook can email):
tomorrow's predicted hotspots, today's recommended patrol roster, flagged events,
and the value at stake.

    python src/digest.py

OUTPUT
  outputs/daily_digest.md   - markdown brief, ready to send
"""
import sys
from datetime import date
from pathlib import Path
import pandas as pd

sys.path.append(str(Path(__file__).resolve().parents[1]))
from config import OUT_DIR, OPT


def _csv(name):
    p = OUT_DIR / name
    return pd.read_csv(p) if p.exists() else pd.DataFrame()


def main():
    today = date.today().isoformat()
    hot = _csv("hotspots.csv")
    plan = _csv("deployment_plan.csv")
    fc = _csv("forecast_hotspots.csv")
    events = _csv("events.csv")
    disp = _csv("displacement_report.csv")

    K = OPT["patrol_slots_per_day"]
    n_viol = int(hot["n_tickets"].sum()) if len(hot) else 0
    n_crit = int((hot["tier"] == "Critical").sum()) if len(hot) else 0
    L = []
    L.append(f"# 🚦 Gridlock — Daily Enforcement Digest")
    L.append(f"**{today}**  ·  auto-generated parking-congestion brief\n")

    # at-a-glance
    L.append("## At a glance")
    L.append(f"- **{n_viol:,}** illegal-parking violations across **{len(hot):,}** zones "
             f"(**{n_crit}** critical hotspots)")
    if len(plan):
        roster = plan.head(K)
        cap = roster["cum_captured_%"].iloc[-1]
        loc = roster["cum_located_%"].iloc[-1]
        L.append(f"- Deploying **{K} patrol-shifts** to the points below covers "
                 f"**{loc:.0f}%** of all violations (≈ **{cap:.0f}%** realistically captured)")
    if len(events):
        L.append(f"- **{len(events):,}** event/surge days on record — watch repeat-spike zones")
    L.append("")

    # today's roster
    if len(plan):
        L.append(f"## Today's patrol roster (top {min(K,12)})")
        L.append("| # | Where | Police station | When | Day | Violations | Note |")
        L.append("|--:|-------|----------------|------|-----|-----------:|------|")
        for _, r in plan.head(min(K, 12)).iterrows():
            note = "🔁 corridor" if r.get("corridor", False) else ""
            L.append(f"| {int(r['priority'])} | {r['junction_name']} | "
                     f"{r['police_station']} | {r['window']} | {r['busiest_dow']} | "
                     f"{int(r['violations']):,} | {note} |")
        L.append("")

    # next-week forecast
    if len(fc):
        L.append("## Predicted hotspots — next 7 days")
        L.append("| # | Where | Police station | Predicted tickets |")
        L.append("|--:|-------|----------------|------------------:|")
        for _, r in fc.head(8).iterrows():
            L.append(f"| {int(r['rank'])} | {r['junction_name']} | "
                     f"{r['police_station']} | {r['pred_week']:.0f} |")
        L.append("")

    # displacement watch-list
    if len(disp):
        wm = disp[disp["verdict"].astype(str).str.startswith("Displacement")]
        if len(wm):
            L.append("## ⚠ Corridor watch-list (enforce as a corridor, not a block)")
            for _, r in wm.head(5).iterrows():
                L.append(f"- **{r['junction_name']}** ({r['police_station']}) — "
                         f"isolated enforcement displaced ~{r['displacement_%']:.0f}% next door")
            L.append("")

    # recent events
    if len(events):
        L.append("## Recent event spikes")
        L.append("| Date | Where | Tickets | Normal | Spike |")
        L.append("|------|-------|--------:|-------:|------:|")
        for _, r in events.head(6).iterrows():
            L.append(f"| {r['date']} | {r['junction_name']} | {int(r['count'])} | "
                     f"{r['normal_day']} | {r['z_score']:.0f}σ |")
        L.append("")

    L.append("---")
    L.append("*Generated by Gridlock. Figures are planning-grade estimates from "
             "detected violations; see config.py for tunable parameters.*")

    out = OUT_DIR / "daily_digest.md"
    out.write_text("\n".join(L), encoding="utf-8")
    print(f"Wrote {out}")
    print(f"  violations {n_viol:,} | roster {min(K,12)} points | "
          f"forecast {len(fc)} zones | events {len(events)}")


if __name__ == "__main__":
    main()
